spring:
  main:
    banner-mode: console
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dummy?currentSchema=service_user
    username: dummy_user
    password: dummy_password
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 9011
  context-path: /user

logging:
  level:
    root: INFO